# Load and split data

In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Parameters

In [14]:
RND_SEED = 123
PCT_TEST = 0.2
TARGET_MAP = {"F": 0, "NF": 1}
# Paths

path_raw = os.path.join("data", "raw")
path_interim = os.path.join("data", "interim")

# Input
file_input = "New%20Spanish%20Academic%20Dataset.csv"

# Output
file_prep = "prep.csv"
file_train = "train.csv"
file_test = "test.csv"

# Load data

In [ ]:
path_data_raw = os.path.join(path_raw, file_input)

df_raw = pd.read_csv(path_data_raw)
df_raw.head()

  PROJECT                                        REQUIREMENT FINAL_LABEL
0      16  Poder crear un usuario y acceder a través de é...          NF
1      16  Poder crear un perfil personal e individual a ...           F
2      16  Acceder a la aplicación y a sus funcionalidade...          NF
3      16  Todos los datos introducidos podrán ser leídos...          NF
4      16  Poder leer, eliminar, editar o incluir cualqui...           F

In [16]:
# Obtain the number or rows and columns
df_raw.shape

(389, 3)

In [17]:
# Calculate the percentage of N and NF rows
df_raw['FINAL_LABEL'].value_counts(normalize=True)

FINAL_LABEL
F     0.771208
NF    0.228792
Name: proportion, dtype: float64

# Transform data

In [19]:
df_raw.columns

Index(['PROJECT', 'REQUIREMENT', 'FINAL_LABEL'], dtype='object')

In [21]:
df_prep = df_raw.copy()
df_prep['y_is_nf'] = np.where(df_raw['FINAL_LABEL']== 'F', 0, 1)
df_prep['x_text'] = df_raw['REQUIREMENT']

df_prep = df_prep[["x_text", "y_is_nf"]]
df_prep

                                                x_text  y_is_nf
0    Poder crear un usuario y acceder a través de é...        1
1    Poder crear un perfil personal e individual a ...        0
2    Acceder a la aplicación y a sus funcionalidade...        1
3    Todos los datos introducidos podrán ser leídos...        1
4    Poder leer, eliminar, editar o incluir cualqui...        0
..                                                 ...      ...
384  Gestión de los errores: El asistente debe esta...        0
385  Respuestas coherentes e idénticas ante entrada...        0
386  Velocidad en las respuestas: El principal serv...        1
387  Facilidad de uso: Las preguntas se deben poder...        1
388  Interfaz atractiva: La interfaz debe integrars...        1

[389 rows x 2 columns]

# Split data

In [22]:
# add parametrized test_size and random_state and add a propper sampling stratgy
# when the input is a single object, the output will maintain the same structure
df_train, df_test = train_test_split(
    df_prep,
    test_size=0.3,
    random_state=23
   
)

print(f"{df_train.shape=}")
print(f"{df_test.shape=}")

df_train.shape=(272, 2)
df_test.shape=(117, 2)

# Write Data

In [23]:
if not os.path.exists(path_interim):
    print("Please, create the folder /data/interim/ !")

df_prep.to_csv(
    os.path.join(path_interim, file_prep),
    index=False)

df_train.to_csv(
    os.path.join(path_interim, file_train),
    index=False)

df_test.to_csv(
    os.path.join(path_interim, file_test),
    index=False)