# Benchmark: Compare experiments and decide the champion architecture

In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
from datetime import datetime
import os
import pandas as pd
from sklearn.metrics import f1_score
from src import models, utils

# Parameters

In [10]:
VERSION_ID = '202602'  # model_version_id
SCORE = "F1"

# Paths
path_interim = os.path.join("data", "interim")
path_experiment1 =  os.path.join(path_interim, "exp01_hpt_nb")
path_experiment2 =  os.path.join(path_interim, "exp02_hpt_gbt")
path_model_prod = os.path.join("models", "prod")
path_model_arch = os.path.join("models", "archive")

# Input
file_train = "train.csv"
file_test = "test.csv"

In [11]:
if not os.path.exists(path_model_prod):
    print(f"Creating the folder: {path_model_prod}")
    os.mkdir(path_model_prod)
if not os.path.exists(path_model_arch):
    print(f"Creating the folder: {path_model_arch}")
    os.mkdir(path_model_arch)

# Load data

## Train/Test Subsets

In [12]:
path_data_train = os.path.join(path_interim, file_train)

df_train = pd.read_csv(path_data_train)
df_train.head(2)

                                              x_text  y_is_nf
0  Poder crear cualquier mérito y asociarlo a mi ...        0
1  Como usuario autenticado quiero indicar que to...        0

In [13]:
path_data_test = os.path.join(path_interim, file_test)

df_test = pd.read_csv(path_data_test)
df_test.head(2)

                                              x_text  y_is_nf
0  Proporcionará un tablón de eventos dentro de l...        0
1                              Añadir revista nueva.        0

## Experiments results

In [14]:
df_cv_summary_exp1 = pd.read_csv(
    os.path.join(path_experiment1,"df_exp_summary.csv")
)
df_cv_summary_exp1.head(2)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_fte__max_df,param_fte__max_features,param_fte__min_df,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,experiment_id
0,0.328690,0.069224,0.118635,0.007134,0.1,50,1,"{'fte__max_df': 0.1, 'fte__max_features': 50, ...",0.542373,0.597015,0.411765,0.517051,0.077719,41,exp01_hpt_nb
1,0.264642,0.011554,0.114961,0.007888,0.1,50,3,"{'fte__max_df': 0.1, 'fte__max_features': 50, ...",0.571429,0.597015,0.411765,0.526736,0.081965,40,exp01_hpt_nb

In [15]:
df_cv_summary_exp2 = pd.read_csv(
     os.path.join(path_experiment2,"df_exp_summary.csv")
)
df_cv_summary_exp2.head(2)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_clf__max_depth,param_fte__max_df,param_fte__max_features,param_fte__min_df,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,experiment_id
0,1.769881,0.160945,0.081500,0.020005,2,0.1,10,1,"{'clf__max_depth': 2, 'fte__max_df': 0.1, 'fte...",0.2,0.0,0.153846,0.117949,0.085504,169,exp02_hpt_gbt
1,1.714828,0.063025,0.065027,0.004123,2,0.1,10,3,"{'clf__max_depth': 2, 'fte__max_df': 0.1, 'fte...",0.2,0.0,0.000000,0.066667,0.094281,173,exp02_hpt_gbt

# Benchmark

In [16]:
df_cv_summary_exp1.sort_values(ascending=True, by="rank_test_score").head(5)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_fte__max_df,param_fte__max_features,param_fte__min_df,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,experiment_id
26,0.223155,0.010556,0.111054,0.006084,0.25,1000,5,"{'fte__max_df': 0.25, 'fte__max_features': 100...",0.68,0.754717,0.808511,0.747743,0.052696,1,exp01_hpt_nb
29,0.243945,0.016002,0.142250,0.035356,0.25,2000,5,"{'fte__max_df': 0.25, 'fte__max_features': 200...",0.68,0.754717,0.808511,0.747743,0.052696,1,exp01_hpt_nb
23,0.269929,0.044994,0.120188,0.005865,0.25,500,5,"{'fte__max_df': 0.25, 'fte__max_features': 500...",0.68,0.754717,0.808511,0.747743,0.052696,1,exp01_hpt_nb
38,0.267924,0.063077,0.117569,0.002215,0.50,500,5,"{'fte__max_df': 0.5, 'fte__max_features': 500,...",0.68,0.754717,0.808511,0.747743,0.052696,1,exp01_hpt_nb
41,0.237565,0.024427,0.112443,0.003864,0.50,1000,5,"{'fte__max_df': 0.5, 'fte__max_features': 1000...",0.68,0.754717,0.808511,0.747743,0.052696,1,exp01_hpt_nb

In [17]:
df_cv_summary_exp2.sort_values(ascending=True, by="rank_test_score").head(5)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_clf__max_depth,param_fte__max_df,param_fte__max_features,param_fte__min_df,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,experiment_id
23,1.895222,0.158946,0.066013,0.004588,2,0.25,100,5,"{'clf__max_depth': 2, 'fte__max_df': 0.25, 'ft...",0.625000,0.800000,0.585366,0.670122,0.093252,1,exp02_hpt_gbt
38,2.184465,0.039063,0.068256,0.007357,2,0.50,100,5,"{'clf__max_depth': 2, 'fte__max_df': 0.5, 'fte...",0.625000,0.800000,0.585366,0.670122,0.093252,1,exp02_hpt_gbt
41,2.073582,0.070645,0.066723,0.004138,2,0.50,150,5,"{'clf__max_depth': 2, 'fte__max_df': 0.5, 'fte...",0.600000,0.716981,0.634146,0.650376,0.049117,3,exp02_hpt_gbt
26,2.044204,0.234791,0.069008,0.004804,2,0.25,150,5,"{'clf__max_depth': 2, 'fte__max_df': 0.25, 'ft...",0.600000,0.716981,0.634146,0.650376,0.049117,3,exp02_hpt_gbt
24,2.134710,0.029400,0.062239,0.000638,2,0.25,150,1,"{'clf__max_depth': 2, 'fte__max_df': 0.25, 'ft...",0.583333,0.705882,0.651163,0.646793,0.050126,5,exp02_hpt_gbt

In [ ]:
# review params first model
print(df_cv_summary_exp2.params[0])

{'clf__max_depth': 2, 'fte__max_df': 0.1, 'fte__max_features': 10, 'fte__min_df': 1}

# Champion model

In [18]:
df_cv_summary_exp1.loc[
    df_cv_summary_exp1['rank_test_score'] == 1, [
        "mean_test_score", "std_test_score",
        "param_fte__max_df","param_fte__max_features",	"param_fte__min_df"]  # set the params of your champion model
]   # at a tie, you can get the model with : lowest std_test_score and the most simple one

,mean_test_score,std_test_score,param_fte__max_df,param_fte__max_features,param_fte__min_df
23,0.747743,0.052696,0.25,500,5
26,0.747743,0.052696,0.25,1000,5
29,0.747743,0.052696,0.25,2000,5
38,0.747743,0.052696,0.50,500,5
41,0.747743,0.052696,0.50,1000,5
44,0.747743,0.052696,0.50,2000,5

Go to src/models.py and implement get_model()


```python
def get_model(
    # your Hiperparameters:
    min_df: int = 3,
    max_df: float = 0.5,
    ...
):
    """
    Builds and returns a scikit-learn Pipeline for Spanish text classification

    Args:
        min_df (int): Minimum document frequency for vectorizer.
        max_df (float): Maximum document frequency for vectorizer.
        max_features (int, optional): Maximum number of features to include.

    Returns:
        sklearn.pipeline.Pipeline: A pipeline with vectorizer and a classifier.
    """

    
    logging.info("Building pipeline...")

    # Your vectorization strategy
    dtm_transformer = XXXVectorizer(
        ...
    )

    # Your model
    clf = ...


    # Champion pipeline architecture
    skl_pl = Pipeline([
        ('fte', dtm_transformer),
        ('clf', clf)
    ])

    return skl_pl
```

In [ ]:
from src.models import get_model
from sklearn.metrics import accuracy_score

X_train = df_train['x_text']
y_train = df_train['y_is_nf']
X_test = df_test['x_text']
y_test = df_test['y_is_nf']



# Fit champion model on the training data
model = get_model()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Test the results in testing data

test_accuracy = accuracy_score(y_test, y_pred)
print(f"Test accuracy: {test_accuracy:.4f}")

2026-03-18 10:29:30 [INFO] Building pipeline...
/home/estebanm/Escritorio/Master/pc4_nlp/dslab-nlp-pc/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

Test accuracy: 0.8974